# Version
version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.6-alpine3.19
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.4
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=srgr89@gmail.com

# volumes:
#   postgres-db:
#     external: true