services:
  db:
    container_name: postgres_database
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgAdmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4:8.9    
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "8080:80"

volumes:
  postgres_data:
  pgadmin_data: